### ISSUE TITLE
Unable to Import in Angular

### ISSUE THREAD

**Issue by hirocsingh** [sashee/aws-svg-icons#1]
After installing the latest version through `npm` I was unable to import the icons in my components. Is it different from how we import in React ?

![image](https://user-images.githubusercontent.com/21228750/126022491-d22ad464-c5d4-49c4-b964-5731c6b620c2.png)

**Comment by sashee** [comment]
Hey Avinash,

no, it works the same for React and Angular. The problem is that I forgot to update the example in the readme to follow the current structure of the icons.

Try this:
```
import lambdaIcon from "aws-svg-icons/lib/Architecture-Service-Icons_04-30-2021/Arch_Compute/64/Arch_AWS-Lambda_64.svg"
```

You can find the current path for all icons on the demo page: https://sashee.github.io/aws-svg-icons/index.html

The npm package follows the same layout as the zip file AWS publishes and unfortunately they change its structure. So it's likely that the paths will break from version to version.

**Comment by hirocsingh** [comment]
Thanks, works now.
